'
' Target: Microsoft Access 
' 
' Date  : Feb 28 2018 20:34
' Script Generated by Database Design Studio 2.21.2 
'



'
' Create Table    : 'Email'   
' ID              :  
' Email           :  
'
CREATE TABLE Email (
    ID             LONG NOT NULL,
    Email          LONGTEXT,
CONSTRAINT pk_Email PRIMARY KEY (ID));

'
' Create Table    : 'PrimaryAdress'   
' ID              :  
' StreetName      :  
' HouseNumber     :  
' ZipCode         :  
' CityName        :  
'
CREATE TABLE PrimaryAdress (
    ID             LONG NOT NULL,
    StreetName     LONGTEXT NOT NULL,
    HouseNumber    LONGTEXT NOT NULL,
    ZipCode        LONGTEXT NOT NULL,
    CityName       LONGTEXT NOT NULL,
CONSTRAINT pk_PrimaryAdress PRIMARY KEY (ID));

'
' Create Table    : 'AlternativeAdress'   
' ID              :  
' StreetName      :  
' HouseNumber     :  
' ZipCode         :  
' CityName        :  
'
CREATE TABLE AlternativeAdress (
    ID             LONG NOT NULL,
    StreetName     LONGTEXT NOT NULL,
    HouseNumber    LONGTEXT NOT NULL,
    ZipCode        LONGTEXT NOT NULL,
    CityName       LONGTEXT NOT NULL,
CONSTRAINT pk_AlternativeAdress PRIMARY KEY (ID));

'
' Create Table    : 'Person'   
' ID              :  
' GivenName       :  
' MiddleName      :  
' FamilyName      :  
' ID1             :  (references Email.ID)
' ID2             :  (references PrimaryAdress.ID)
'
CREATE TABLE Person (
    ID             LONG NOT NULL,
    GivenName      LONGTEXT,
    MiddleName     LONGTEXT,
    FamilyName     LONGTEXT,
    ID1            LONG NOT NULL,
    ID2            LONG NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY (ID),
CONSTRAINT fk_Person FOREIGN KEY (ID1)
    REFERENCES Email (ID),
CONSTRAINT fk_Person2 FOREIGN KEY (ID2)
    REFERENCES PrimaryAdress (ID));

'
' Create Table    : 'Telephone'   
' ID              :  
' TelephoneNumber :  
' UsageOfTlf      :  
' PhoneCompany    :  
' ID1             :  (references Person.ID)
'
CREATE TABLE Telephone (
    ID             LONG NOT NULL,
    TelephoneNumber LONGTEXT NOT NULL,
    UsageOfTlf     LONGTEXT NOT NULL,
    PhoneCompany   LONGTEXT NOT NULL,
    ID1            LONG,
CONSTRAINT pk_Telephone PRIMARY KEY (ID),
CONSTRAINT fk_Telephone FOREIGN KEY (ID1)
    REFERENCES Person (ID));

'
' Create Table    : 'TypeOfAdr'   
' ID              :  (references Person.ID)
' ID1             :  (references AlternativeAdress.ID)
' TypeOfAdr       :  
'
CREATE TABLE TypeOfAdr (
    ID             LONG NOT NULL,
    ID1            LONG NOT NULL,
    TypeOfAdr      LONGTEXT NOT NULL,
CONSTRAINT pk_TypeOfAdr PRIMARY KEY (ID,ID1),
CONSTRAINT fk_TypeOfAdr FOREIGN KEY (ID)
    REFERENCES Person (ID),
CONSTRAINT fk_TypeOfAdr2 FOREIGN KEY (ID1)
    REFERENCES AlternativeAdress (ID));

