#
# Target: MySQL 
# Syntax: mysql -u user password < filename.sql
# 
# Date  : Feb 28 2018 20:34
# Script Generated by Database Design Studio 2.21.2 
#

#
# Select Database: 'db_name'
#
USE db_name;
#
# Load Table : 'Email' 
#
LOAD DATA
INFILE 'Email.txt' 
INTO TABLE Email
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

#
# Load Table : 'PrimaryAdress' 
#
LOAD DATA
INFILE 'PrimaryAdress.txt' 
INTO TABLE PrimaryAdress
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

#
# Load Table : 'AlternativeAdress' 
#
LOAD DATA
INFILE 'AlternativeAdress.txt' 
INTO TABLE AlternativeAdress
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

#
# Load Table : 'Person' 
#
LOAD DATA
INFILE 'Person.txt' 
INTO TABLE Person
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

#
# Load Table : 'Telephone' 
#
LOAD DATA
INFILE 'Telephone.txt' 
INTO TABLE Telephone
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

#
# Load Table : 'TypeOfAdr' 
#
LOAD DATA
INFILE 'TypeOfAdr.txt' 
INTO TABLE TypeOfAdr
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

