#
# Target: MySQL 
# Syntax: mysql -u user password < filename.sql
# 
# Date  : Feb 28 2018 20:34
# Script Generated by Database Design Studio 2.21.2 
#


#
# Select Database: 'db_name'
#
USE db_name;

#
# Create Table    : 'Email'   
# ID              :  
# Email           :  
#
CREATE TABLE Email (
    ID             BIGINT NOT NULL,
    Email          #### NULL,
PRIMARY KEY (ID)) TYPE=INNODB;

#
# Create Table    : 'PrimaryAdress'   
# ID              :  
# StreetName      :  
# HouseNumber     :  
# ZipCode         :  
# CityName        :  
#
CREATE TABLE PrimaryAdress (
    ID             BIGINT NOT NULL,
    StreetName     #### NOT NULL,
    HouseNumber    #### NOT NULL,
    ZipCode        #### NOT NULL,
    CityName       #### NOT NULL,
PRIMARY KEY (ID)) TYPE=INNODB;

#
# Create Table    : 'AlternativeAdress'   
# ID              :  
# StreetName      :  
# HouseNumber     :  
# ZipCode         :  
# CityName        :  
#
CREATE TABLE AlternativeAdress (
    ID             BIGINT NOT NULL,
    StreetName     #### NOT NULL,
    HouseNumber    #### NOT NULL,
    ZipCode        #### NOT NULL,
    CityName       #### NOT NULL,
PRIMARY KEY (ID)) TYPE=INNODB;

#
# Create Table    : 'Person'   
# ID              :  
# GivenName       :  
# MiddleName      :  
# FamilyName      :  
# ID1             :  (references Email.ID)
# ID2             :  (references PrimaryAdress.ID)
#
CREATE TABLE Person (
    ID             BIGINT NOT NULL,
    GivenName      #### NULL,
    MiddleName     #### NULL,
    FamilyName     #### NULL,
    ID1            BIGINT NOT NULL,
    ID2            BIGINT NOT NULL,
PRIMARY KEY (ID),
    INDEX idx_fk_Person (ID1),
CONSTRAINT fk_Person FOREIGN KEY (ID1)
    REFERENCES Email (ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    INDEX idx_fk_Person2 (ID2),
CONSTRAINT fk_Person2 FOREIGN KEY (ID2)
    REFERENCES PrimaryAdress (ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE) TYPE=INNODB;

#
# Create Table    : 'Telephone'   
# ID              :  
# TelephoneNumber :  
# UsageOfTlf      :  
# PhoneCompany    :  
# ID1             :  (references Person.ID)
#
CREATE TABLE Telephone (
    ID             BIGINT NOT NULL,
    TelephoneNumber #### NOT NULL,
    UsageOfTlf     #### NOT NULL,
    PhoneCompany   #### NOT NULL,
    ID1            BIGINT NULL,
PRIMARY KEY (ID),
    INDEX idx_fk_Telephone (ID1),
CONSTRAINT fk_Telephone FOREIGN KEY (ID1)
    REFERENCES Person (ID)
    ON DELETE SET NULL
    ON UPDATE CASCADE) TYPE=INNODB;

#
# Create Table    : 'TypeOfAdr'   
# ID              :  (references Person.ID)
# ID1             :  (references AlternativeAdress.ID)
# TypeOfAdr       :  
#
CREATE TABLE TypeOfAdr (
    ID             BIGINT NOT NULL,
    ID1            BIGINT NOT NULL,
    TypeOfAdr      #### NOT NULL,
PRIMARY KEY (ID,ID1),
    INDEX idx_fk_TypeOfAdr (ID),
CONSTRAINT fk_TypeOfAdr FOREIGN KEY (ID)
    REFERENCES Person (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    INDEX idx_fk_TypeOfAdr2 (ID1),
CONSTRAINT fk_TypeOfAdr2 FOREIGN KEY (ID1)
    REFERENCES AlternativeAdress (ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE) TYPE=INNODB;

#
# Permissions for: 'public'
#;

