--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Feb 28 2018 20:34
-- Script Generated by Database Design Studio 2.21.2 
--


--
-- Select Database: 'db_name'
--
USE db_name
GO
 
IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Create Table    : 'Email'   
-- ID              :  
-- Email           :  
--
CREATE TABLE Email (
    ID             BIGINT NOT NULL,
    Email          NVARCHAR NULL,
CONSTRAINT pk_Email PRIMARY KEY CLUSTERED (ID))
GO

--
-- Create Table    : 'PrimaryAdress'   
-- ID              :  
-- StreetName      :  
-- HouseNumber     :  
-- ZipCode         :  
-- CityName        :  
--
CREATE TABLE PrimaryAdress (
    ID             BIGINT NOT NULL,
    StreetName     NVARCHAR NOT NULL,
    HouseNumber    NVARCHAR NOT NULL,
    ZipCode        NVARCHAR NOT NULL,
    CityName       NVARCHAR NOT NULL,
CONSTRAINT pk_PrimaryAdress PRIMARY KEY CLUSTERED (ID))
GO

--
-- Create Table    : 'AlternativeAdress'   
-- ID              :  
-- StreetName      :  
-- HouseNumber     :  
-- ZipCode         :  
-- CityName        :  
--
CREATE TABLE AlternativeAdress (
    ID             BIGINT NOT NULL,
    StreetName     NVARCHAR NOT NULL,
    HouseNumber    NVARCHAR NOT NULL,
    ZipCode        NVARCHAR NOT NULL,
    CityName       NVARCHAR NOT NULL,
CONSTRAINT pk_AlternativeAdress PRIMARY KEY CLUSTERED (ID))
GO

--
-- Create Table    : 'Person'   
-- ID              :  
-- GivenName       :  
-- MiddleName      :  
-- FamilyName      :  
-- ID1             :  (references Email.ID)
-- ID2             :  (references PrimaryAdress.ID)
--
CREATE TABLE Person (
    ID             BIGINT NOT NULL,
    GivenName      NVARCHAR NULL,
    MiddleName     NVARCHAR NULL,
    FamilyName     NVARCHAR NULL,
    ID1            BIGINT NOT NULL,
    ID2            BIGINT NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (ID),
CONSTRAINT fk_Person FOREIGN KEY (ID1)
    REFERENCES Email (ID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
CONSTRAINT fk_Person2 FOREIGN KEY (ID2)
    REFERENCES PrimaryAdress (ID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Telephone'   
-- ID              :  
-- TelephoneNumber :  
-- UsageOfTlf      :  
-- PhoneCompany    :  
-- ID1             :  (references Person.ID)
--
CREATE TABLE Telephone (
    ID             BIGINT NOT NULL,
    TelephoneNumber NVARCHAR NOT NULL,
    UsageOfTlf     NVARCHAR NOT NULL,
    PhoneCompany   NVARCHAR NOT NULL,
    ID1            BIGINT NULL,
CONSTRAINT pk_Telephone PRIMARY KEY CLUSTERED (ID),
CONSTRAINT fk_Telephone FOREIGN KEY (ID1)
    REFERENCES Person (ID)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'TypeOfAdr'   
-- ID              :  (references Person.ID)
-- ID1             :  (references AlternativeAdress.ID)
-- TypeOfAdr       :  
--
CREATE TABLE TypeOfAdr (
    ID             BIGINT NOT NULL,
    ID1            BIGINT NOT NULL,
    TypeOfAdr      NVARCHAR(1) NOT NULL,
CONSTRAINT pk_TypeOfAdr PRIMARY KEY CLUSTERED (ID,ID1),
CONSTRAINT fk_TypeOfAdr FOREIGN KEY (ID)
    REFERENCES Person (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_TypeOfAdr2 FOREIGN KEY (ID1)
    REFERENCES AlternativeAdress (ID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Email TO public
GO
GRANT ALL ON PrimaryAdress TO public
GO
GRANT ALL ON AlternativeAdress TO public
GO
GRANT ALL ON Person TO public
GO
GRANT ALL ON Telephone TO public
GO
GRANT ALL ON TypeOfAdr TO public
GO

