--
-- Target: Adaptive Server Enterprise ASE 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Feb 28 2018 20:34
-- Script Generated by Database Design Studio 2.21.2 
--

--
-- Select Database: 'db_name'
--
USE db_name
GO
 
IF DB_NAME() = 'db_name'
    PRINT '''db_name'' DATABASE CONTEXT NOW IN USE.'
-- ELSE
--     RAISERROR 0000 'ERROR IN BATCH FILE, ''USE db_name'' FAILED!'
-- if you want to use RAISERROR you need to create a System Error number,
-- replace the 0000 above with the error number and uncomment the above
-- in the Sybase-ASE.tpl template file
 
GO
execute master..sp_dboption 'db_name' ,'trunc. log on chkpt.' , true
GO
--
-- Drop Table    : 'TypeOfAdr'   
--
DROP TABLE TypeOfAdr
GO
--
-- Drop Table    : 'Telephone'   
--
DROP TABLE Telephone
GO
--
-- Drop Table    : 'Person'   
--
DROP TABLE Person
GO
--
-- Drop Table    : 'AlternativeAdress'   
--
DROP TABLE AlternativeAdress
GO
--
-- Drop Table    : 'PrimaryAdress'   
--
DROP TABLE PrimaryAdress
GO
--
-- Drop Table    : 'Email'   
--
DROP TABLE Email
GO
