--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : Feb 28 2018 20:34
-- Script Generated by Database Design Studio 2.21.2 
--

--
-- Drop Table    : 'TypeOfAdr'   
--
DROP TABLE TypeOfAdr
/
--
-- Drop Table    : 'Telephone'   
--
DROP TABLE Telephone
/
--
-- Drop Table    : 'Person'   
--
DROP TABLE Person
/
--
-- Drop Table    : 'AlternativeAdress'   
--
DROP TABLE AlternativeAdress
/
--
-- Drop Table    : 'PrimaryAdress'   
--
DROP TABLE PrimaryAdress
/
--
-- Drop Table    : 'Email'   
--
DROP TABLE Email
/
exit;

