--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : Feb 28 2018 20:34
-- Script Generated by Database Design Studio 2.21.2 
--



--
-- Create Table    : 'Email'   
-- ID              :  
-- Email           :  
--
CREATE TABLE Email (
    ID             NUMBER(38) NOT NULL,
    Email          NVARCHAR2,
CONSTRAINT pk_Email PRIMARY KEY (ID))
/


--
-- Create Table    : 'PrimaryAdress'   
-- ID              :  
-- StreetName      :  
-- HouseNumber     :  
-- ZipCode         :  
-- CityName        :  
--
CREATE TABLE PrimaryAdress (
    ID             NUMBER(38) NOT NULL,
    StreetName     NVARCHAR2 NOT NULL,
    HouseNumber    NVARCHAR2 NOT NULL,
    ZipCode        NVARCHAR2 NOT NULL,
    CityName       NVARCHAR2 NOT NULL,
CONSTRAINT pk_PrimaryAdress PRIMARY KEY (ID))
/


--
-- Create Table    : 'AlternativeAdress'   
-- ID              :  
-- StreetName      :  
-- HouseNumber     :  
-- ZipCode         :  
-- CityName        :  
--
CREATE TABLE AlternativeAdress (
    ID             NUMBER(38) NOT NULL,
    StreetName     NVARCHAR2 NOT NULL,
    HouseNumber    NVARCHAR2 NOT NULL,
    ZipCode        NVARCHAR2 NOT NULL,
    CityName       NVARCHAR2 NOT NULL,
CONSTRAINT pk_AlternativeAdress PRIMARY KEY (ID))
/


--
-- Create Table    : 'Person'   
-- ID              :  
-- GivenName       :  
-- MiddleName      :  
-- FamilyName      :  
-- ID1             :  (references Email.ID)
-- ID2             :  (references PrimaryAdress.ID)
--
CREATE TABLE Person (
    ID             NUMBER(38) NOT NULL,
    GivenName      NVARCHAR2,
    MiddleName     NVARCHAR2,
    FamilyName     NVARCHAR2,
    ID1            NUMBER(38) NOT NULL,
    ID2            NUMBER(38) NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY (ID),
CONSTRAINT fk_Person FOREIGN KEY (ID1)
    REFERENCES Email (ID),
CONSTRAINT fk_Person2 FOREIGN KEY (ID2)
    REFERENCES PrimaryAdress (ID))
/


--
-- Create Table    : 'Telephone'   
-- ID              :  
-- TelephoneNumber :  
-- UsageOfTlf      :  
-- PhoneCompany    :  
-- ID1             :  (references Person.ID)
--
CREATE TABLE Telephone (
    ID             NUMBER(38) NOT NULL,
    TelephoneNumber NVARCHAR2 NOT NULL,
    UsageOfTlf     NVARCHAR2 NOT NULL,
    PhoneCompany   NVARCHAR2 NOT NULL,
    ID1            NUMBER(38),
CONSTRAINT pk_Telephone PRIMARY KEY (ID),
CONSTRAINT fk_Telephone FOREIGN KEY (ID1)
    REFERENCES Person (ID))
/


--
-- Create Table    : 'TypeOfAdr'   
-- ID              :  (references Person.ID)
-- ID1             :  (references AlternativeAdress.ID)
-- TypeOfAdr       :  
--
CREATE TABLE TypeOfAdr (
    ID             NUMBER(38) NOT NULL,
    ID1            NUMBER(38) NOT NULL,
    TypeOfAdr      NVARCHAR2(1) NOT NULL,
CONSTRAINT pk_TypeOfAdr PRIMARY KEY (ID,ID1),
CONSTRAINT fk_TypeOfAdr FOREIGN KEY (ID)
    REFERENCES Person (ID)
    ON DELETE CASCADE,
CONSTRAINT fk_TypeOfAdr2 FOREIGN KEY (ID1)
    REFERENCES AlternativeAdress (ID))
/


--
-- Permissions for: 'public'
--
GRANT ALL ON Email TO public
/
GRANT ALL ON PrimaryAdress TO public
/
GRANT ALL ON AlternativeAdress TO public
/
GRANT ALL ON Person TO public
/
GRANT ALL ON Telephone TO public
/
GRANT ALL ON TypeOfAdr TO public
/

exit;

