--
-- Target: Pervasive SQL V8
-- Date  : Feb 28 2018 20:34
-- Script Generated by Database Design Studio 2.21.2 
--



--
-- Create Table    : 'Email'   
-- ID              :  
-- Email           :  
--
CREATE TABLE Email (
    ID             BIGINT NOT NULL,
    Email          LONGVARCHAR,
PRIMARY KEY (ID))
GO

--
-- Create Table    : 'PrimaryAdress'   
-- ID              :  
-- StreetName      :  
-- HouseNumber     :  
-- ZipCode         :  
-- CityName        :  
--
CREATE TABLE PrimaryAdress (
    ID             BIGINT NOT NULL,
    StreetName     LONGVARCHAR NOT NULL,
    HouseNumber    LONGVARCHAR NOT NULL,
    ZipCode        LONGVARCHAR NOT NULL,
    CityName       LONGVARCHAR NOT NULL,
PRIMARY KEY (ID))
GO

--
-- Create Table    : 'AlternativeAdress'   
-- ID              :  
-- StreetName      :  
-- HouseNumber     :  
-- ZipCode         :  
-- CityName        :  
--
CREATE TABLE AlternativeAdress (
    ID             BIGINT NOT NULL,
    StreetName     LONGVARCHAR NOT NULL,
    HouseNumber    LONGVARCHAR NOT NULL,
    ZipCode        LONGVARCHAR NOT NULL,
    CityName       LONGVARCHAR NOT NULL,
PRIMARY KEY (ID))
GO

--
-- Create Table    : 'Person'   
-- ID              :  
-- GivenName       :  
-- MiddleName      :  
-- FamilyName      :  
-- ID1             :  (references Email.ID)
-- ID2             :  (references PrimaryAdress.ID)
--
CREATE TABLE Person (
    ID             BIGINT NOT NULL,
    GivenName      LONGVARCHAR,
    MiddleName     LONGVARCHAR,
    FamilyName     LONGVARCHAR,
    ID1            BIGINT NOT NULL,
    ID2            BIGINT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID1)
    REFERENCES Email (ID)
    ON DELETE RESTRICT,
FOREIGN KEY (ID2)
    REFERENCES PrimaryAdress (ID)
    ON DELETE RESTRICT)
GO

--
-- Create Table    : 'Telephone'   
-- ID              :  
-- TelephoneNumber :  
-- UsageOfTlf      :  
-- PhoneCompany    :  
-- ID1             :  (references Person.ID)
--
CREATE TABLE Telephone (
    ID             BIGINT NOT NULL,
    TelephoneNumber LONGVARCHAR NOT NULL,
    UsageOfTlf     LONGVARCHAR NOT NULL,
    PhoneCompany   LONGVARCHAR NOT NULL,
    ID1            BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (ID1)
    REFERENCES Person (ID)
 )
GO

--
-- Create Table    : 'TypeOfAdr'   
-- ID              :  (references Person.ID)
-- ID1             :  (references AlternativeAdress.ID)
-- TypeOfAdr       :  
--
CREATE TABLE TypeOfAdr (
    ID             BIGINT NOT NULL,
    ID1            BIGINT NOT NULL,
    TypeOfAdr      LONGVARCHAR NOT NULL,
PRIMARY KEY (ID,ID1),
FOREIGN KEY (ID)
    REFERENCES Person (ID)
    ON DELETE CASCADE,
FOREIGN KEY (ID1)
    REFERENCES AlternativeAdress (ID)
    ON DELETE RESTRICT)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Email TO public
GO
GRANT ALL ON PrimaryAdress TO public
GO
GRANT ALL ON AlternativeAdress TO public
GO
GRANT ALL ON Person TO public
GO
GRANT ALL ON Telephone TO public
GO
GRANT ALL ON TypeOfAdr TO public
GO

