--
-- Target: Pervasive SQL V8
-- Date  : Feb 28 2018 20:34
-- Script Generated by Database Design Studio 2.21.2 
--

--
-- Drop Table    : 'TypeOfAdr'   
--
DROP TABLE TypeOfAdr
GO
--
-- Drop Table    : 'Telephone'   
--
DROP TABLE Telephone
GO
--
-- Drop Table    : 'Person'   
--
DROP TABLE Person
GO
--
-- Drop Table    : 'AlternativeAdress'   
--
DROP TABLE AlternativeAdress
GO
--
-- Drop Table    : 'PrimaryAdress'   
--
DROP TABLE PrimaryAdress
GO
--
-- Drop Table    : 'Email'   
--
DROP TABLE Email
GO
